version: "3"

networks:
  web:
    external: true

services:
  frontend:
    container_name: frontend
    image: sharkyrekin/bobby-frontend:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: NextJS.Dockerfile
    networks:
      - web
    labels:
      - traefik.http.routers.frontend.rule=Host(`idea-student.works`)
      - traefik.http.routers.frontend.tls=true
      - traefik.http.routers.frontend.tls.certresolver=lets-encrypt
      - traefik.http.services.frontend.loadbalancer.server.port=3000
      - traefik.port=80
  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: .
      dockerfile: Pocketbase.Dockerfile
    networks:
      - web
    labels:
      - traefik.http.routers.backend.rule=Host(`pocketbase.idea-student.works`)
      - traefik.http.routers.backend.tls=true
      - traefik.http.routers.backend.tls.certresolver=lets-encrypt
      - traefik.http.services.backend.loadbalancer.server.port=9090
      - traefik.port=80
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5